[phases.setup]
nixPkgs = [
    "...",
    "pango",
    "cairo",
    "gdk-pixbuf",
    "glib",
    "harfbuzz",
    "fontconfig",
    "freetype",
    "shared-mime-info",
]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]